# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakefactory', '0002_auto_20170316_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('customer', 'current')]),
        ),
    ]
