# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakefactory', '0004_orderitem_related_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([]),
        ),
    ]
